### PR TITLE
bird: Update to v2.0.2

### PR DESCRIPTION
**Pull request by tohojo**
Add a couple of backported patches that fixes the build version + a couple
of fixes to the Babel implementation. Also update the init file to use procd.

Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>

This is based on, and supersedes, https://github.com/openwrt-routing/packages/pull/340

This just replaced the old 1.6 version with 2.0. The stability issues should be fixed with 2.0.2 + the backported patches included here. There is the issue of config compatibility, which could be a reason to keep the old version around, but if that is a concern I'd suggest keeping a compatibility package for bird 1.6 and having 2.0 be the 'main' version...

### CODE REVIEW

**Comment by tohojo** [comment]
Cc @Noltari  @eloicaso @p4u

**Comment by mwarning** [comment]
Do you also get this warning message?
```
[mwarning@xanax openwrt]$ make defconfig
WARNING: Makefile 'package/feeds/routing/bird4-openwrt/Makefile' has a dependency on 'bird4', which does not exist
WARNING: Makefile 'package/feeds/routing/bird6-openwrt/Makefile' has a dependency on 'bird6', which does not exist
```

**Comment by tohojo** [comment]
Ah, yeah, bird-openwrt only works with bird1. See https://github.com/openwrt-routing/packages/issues/277

I guess that a decision needs to be made on whether to keep that and/or update it. Maybe it is better to package both versions of Bird for now, then... I'll things to allow that and open a new pull request.

**Comment by mwarning** [comment]
Maybe rename the package to bird2.

(the existence of bird4 and bird6 are a bit silly)

**Comment by tohojo** [comment]
I did, in the updated pull request: https://github.com/openwrt-routing/packages/pull/378

**Comment by eloicaso** [comment]
Already commented on #378, moving to bird2 makes sense as the ipv4/6 bird instances are just options and not part of the binary name.

I agree that once bird-openwrt is updated to use the new v2 features it will be much nicer to use avoiding the old bird4/6 calls and double packaging.

I'll keep you updated when I have something worth sharing.

**Pull request closed without merging**
