### PR TITLE
openwrt-18.06: batman-adv: Merge bugfixes from 2018.3

### PR DESCRIPTION
**Pull request by ecsv**
* Avoid probe ELP information leak
* Fix segfault when writing to throughput_override
* Fix segfault when writing to sysfs elp_interval
* fix backbone_gw refcount on queue_work() failure
* fix hardif_neigh refcount on queue_work() failure
* Prevent duplicated gateway_node entry
* Prevent duplicated nc_node entry
* Prevent duplicated softif_vlan entry
* Prevent duplicated global TT entry
* Prevent duplicated tvlv handler

----

@simonwunderlich

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
So openwrt-18.06 is supposed to stay on 2018.1?

**Comment by ecsv** [comment]
Yes. Why would expect a switch from batman-adv 2018.1 to something else? You will also hopefully see no switch to Linux 4.19 in OpenWrt 18.06.

**Comment by adrianschmutzler** [comment]
Okay, I just was a little surprised that there was no bugfix backport for 2018.2 but now for 2018.3, so I was interested in the policies behind... (I benefit from the 2018.2 bugfixes, and therefore using the master since then)

**Comment by ecsv** [comment]
Hu? You didn't see the two bugfix backports during the 2018.2 development?

* 2dfb228764144b1b5b4a48f47fb0422fff2c0d7a ("batman-adv: add patches from 2018.1-maint 2018-06-03")
* 87cba7f8996a57122c95fa919e9e5c49e297c112 ("batman-adv: add patches from 2018.1-maint 2018-06-12")

**Comment by adrianschmutzler** [comment]
Oh, cool.
Sorry, I stupidly overlooked them since (for obvious reasons) there was no reference to "2018.2".

**Pull request merged**
