### PR TITLE
BIRD: Update to version 2.0.8 and small reordering in Makefile

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @tohojo
Run and compile tested: Turris MOX, mvebu/cortexa53, OpenWrt 19.07.7

Changes:
- update to version [2.0.8](https://bird.network.cz/pipermail/bird-users/2021-March/015281.html)
- small shuffling in Makefile + fixed deprecated [SPDX License Identifier](https://spdx.org/licenses/)

Would it be possible to _cherry-pick_ **the update** it to ``openwrt-21.02`` and ``openwrt-19.07`` branches or should I create PR?

### CODE REVIEW

**Comment by tohojo** [comment]
The other patch has also been merged upstream - how is that not giving you build errors?

**Comment by BKPepe** [comment]
It works with the patch, but yeah, I see it was merged upstream. Interesting.

```
. /foo/mox-hbl/build/include/shell.sh; gzip -dc /foo/mox-hbl/build/dl/bird-2.0.8.tar.gz | tar -C /foo/mox-hbl/build/build_dir/target-aarch64_cortex-a53_musl/bird-2.0.8/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /foo/mox-hbl/build/build_dir/target-aarch64_cortex-a53_musl/bird-2.0.8

Applying ./patches/0001-babel-Set-onlink-flag-for-IPv4-routes-with-unreachab.patch using plaintext: 
patching file proto/babel/babel.c
Hunk #1 succeeded at 667 with fuzz 1 (offset 27 lines).
```

**Comment by BKPepe** [comment]
v1 → v2:

- removed patch, so it does not applied twice, still not sure why I was able to compile it with the patch.
- removed option `--with-linux-headers`
**Fixes: configure: WARNING: unrecognized options: --with-linux-headers**

**Review by tohojo — APPROVED** [review]
LGTM - thanks for doing this!

Unfortunately I don't have commit access, so can't actually merge this, but maybe @neheb or @mwarning can take care of that bit? :)

**Comment by mwarning** [comment]
@BKPepe please create MRs for the other branches.

**Comment by BKPepe** [comment]
Will do, thanks.

**Pull request merged**
