### PR TITLE
cjdns: update to 21

### PR DESCRIPTION
**Pull request by neheb**
Fixed compilation with musl 1.2.x , mostly.

Added a patch fixing compilation on 32-bit platforms.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
ping @wfleurant

**Comment by neheb** [comment]
ping @mwarning

**Comment by mwarning** [comment]
@neheb awesome, thanks.

**Comment by wfleurant** [comment]
@neheb thanks

**Pull request merged**
