### PR TITLE
prince: renamed folder

### PR DESCRIPTION
**Pull request by gabri94**
#288 
Signed-off-by: Gabriele Gemmi <gabriel@autistici.org>

### CODE REVIEW

**Comment by mwarning** [comment]
Mantainer => MAINTAINER

**Comment by mwarning** [comment]
I do not know what MENU does. I think you can remove it.
Also, PKG_MD5SUM and  PKG_LICENSE seem to be missing.
See https://spdx.org/licenses/ for apropiate values for PKG_LICENSE (like MIT).

Happy hacking.

**Comment by gabri94** [comment]
with MENU setted as 1 my package had a sort of empty submenu. Probably the default value is 0, thus i can remove it.

**Comment by gabri94** [comment]
@mwarning  regarding the md5um:
For another package in the packages feed (see https://github.com/openwrt/packages/pull/4103)
the user @diizzyy told me to use "PKG_MIRROR_HASH" 
do you know what is the difference?

**Comment by diizzyy** [comment]
@gabri94 
Read the link?

**Comment by gabri94** [comment]
Sorry, I had missed the line 
"Note: PKG_HASH is the successor for PKG_MD5SUM that is being deprecated."
Now it's all clear, thanks

**Comment by mwarning** [comment]
@gabri94 As far as I remember when I've met you last week, this ticket can be closed since you want to create a new one anyway.

**Pull request closed without merging**
