### PR TITLE
babeld: Add procd support and other fixes

### PR DESCRIPTION
**Pull request by zorun**
Based on the work of @imuli with some changes.

### CODE REVIEW

**Comment by zorun** [comment]
@kerneis @jech any objection against merging this?

I refreshed the procd support from @imuli because of changes introduced since then, and babeld now logs to `logread` by default (instead of `/var/log/babeld.log`).  The rest consists of small fixes.

**Comment by zorun** [comment]
By the way, I found a router running OpenWRT CC with babeld, so I tested these changes.  I should hope that it still works with newer versions of OpenWRT/LEDE.

**Comment by kerneis** [comment]
Looks good to me, @zorun (although I have not tested it for real).
Thanks a lot for your help.


Feel free to update the maintainer to yourself if you wish. If you'd
rather not, I'm fine with keeping it as is ;-)


-- 

Gabriel

**Comment by zorun** [comment]
@kerneis Ok, will do :)  I think I will add myself as maintainer then (but also keep you).

**Pull request merged**
