### PR TITLE
mrd6: remove build timestamp

### PR DESCRIPTION
**Pull request by lynxis**
Build timestamp prevents reproducible builds [0].

[0] https://reproducible-builds.org/docs/timestamps/

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

### CODE REVIEW

**Comment by lynxis** [comment]
@dangowrt @altergui

**Comment by lynxis** [comment]
Also see
https://tests.reproducible-builds.org/lede/lede_ar71xx.html
https://tests.reproducible-builds.org/lede/dbd/packages/mips_24kc/routing/mrd6_2013-11-30-c805eb33255dbc0b6647d463c6c67d1c9d3105a0-1_mips_24kc.ipk.html

**Comment by lynxis** [comment]
@sbyx

**Comment by mwarning** [comment]
Looks goof to me. +1

**Comment by lynxis** [comment]
ping @sbyx @mwarning @thess

**Comment by sbyx** [comment]
Thx

**Pull request merged**
