### PR TITLE
olsrd: new version number 0.9.5 and new netjson plugin

### PR DESCRIPTION
**Pull request by FreifunkUFO**
version numkber now on 0.9.5
netjson plugin added

### CODE REVIEW

**Comment by FreifunkUFO** [comment]
the mud-plugin has a problem when compiling
the netjson plugin doesnt have uci yet

**Comment by FreifunkUFO** [comment]
the neigh.sh command (and luci-olsr-status-page) didnt work atm. 
workaround is:
uci set olsrd.olsrd_jsoninfo.httpheaders=false; uci commit
but that will make olsr crash when setting this on older olsr-versions!

**Comment by FreifunkUFO** [comment]
i think we need a ticket instead of a pull-request.
neigh.sh command is at https://github.com/openwrt/luci/blob/master/contrib/package/freifunk-common/files/usr/bin/neigh.sh

**Comment by bittorf** [comment]
i will take care of this ticket today and also repair the broken neigh.sh, stay tuned 8-)

**Comment by bittorf** [comment]
here the PullRequest ("ziehbegehren"!) with the fixed neigh.sh for LUCI: https://github.com/openwrt/luci/pull/874

**Comment by bittorf** [comment]
ufo: can you please add a dependency for "CONFIG_PACKAGE_libgps=y" - this fixes the compile-errors for me. the netjson-plugin-ucification can be made later...

**Comment by bittorf** [comment]
please check + test: https://github.com/openwrt-routing/packages/commit/3b14a1c5b6aaf0422374a14998279d9047b0abf7

**Comment by FreifunkUFO** [comment]
luci-olsr-status-page is also involved:
https://github.com/openwrt/luci/blob/master/applications/luci-app-olsr/luasrc/view/status-olsr/neighbors.htm#L15
and
https://github.com/openwrt/luci/blob/master/applications/luci-app-olsr/luasrc/controller/olsr.lua#L90
and
https://github.com/openwrt/luci/blob/master/applications/luci-app-olsr/luasrc/controller/olsr.lua#L378

**Comment by FreifunkUFO** [comment]
etx=4194304 (non-working link) should have a separate color (and text?)
olsr-neigh-1024

**Comment by bittorf** [comment]
thanks ufo, i will take care of this in another pull request.

**Comment by FreifunkUFO** [comment]
i didnt add that libgps, but yeesterday i was checking/testing the compiling of lede-trunk successfully.
do you need help with luci-app-olsr?
i wonder, why there is PKG_VERSION and PKG_SOURCE_VERSION in Makefile, so the version number is printed twice on opkg commands. might be another ticket?

`root@104-31:~# opkg list-installed | grep olsr
luci-app-olsr - git-16.352.65143-1741e55-1
luci-app-olsr-services - git-16.352.65143-1741e55-1
luci-i18n-olsr-de - git-16.352.65143-1741e55-1
olsrd - 0.9.5-v0.9.5
olsrd-mod-dyn-gw-plain - 0.9.5-v0.9.5
olsrd-mod-jsoninfo - 0.9.5-v0.9.5
olsrd-mod-nameservice - 0.9.5-v0.9.5
olsrd-mod-watchdog - 0.9.5-v0.9.5
`

**Comment by bittorf** [comment]
anything left/overseen? is the gpsd-stuff working now? @FreifunkUFO is the luci-stuff working/commited?

**Comment by FreifunkUFO** [comment]
the luci-stuff isnt commited yet. 
i dont have gps, but the olsr-pud-plugin was compiled in my latest test

**Pull request merged**
