### PR TITLE
Update olsrd

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@mwarning

**Comment by PolynomialDivision** [comment]
I made a mistake.

**Comment by mwarning** [comment]
Let me know when this ready for review. :-)

**Comment by PolynomialDivision** [comment]
> Let me know when this ready for review. :-)

I'm currently missing a node to run-test. Could you?

**Comment by PolynomialDivision** [comment]
@mwarning lets see if it works. :) looks good so far.

**Comment by PolynomialDivision** [comment]
```
WARNING: No feed for package 'olsrd/' found
```
Why? @aparcar Any idea?

**Comment by mwarning** [comment]
I tried to perform a run test, but I think the startup script is broken:
```
root@OpenWrt:~# /etc/init.d/olsrd start
olsrd: /etc/init.d/olsrd: olsrd_write_interface() Warning: Interface 'wlan' not found, skipped
root@OpenWrt:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000
    link/ether 20:28:18:a1:53:4e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2228:18ff:fea1:534e/64 scope link 
       valid_lft forever preferred_lft forever
4: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 20:28:18:a1:53:4e brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fd1a:e14a:2e84::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::2228:18ff:fea1:534e/64 scope link 
       valid_lft forever preferred_lft forever
5: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP qlen 1000
    link/ether 20:28:18:a1:53:4e brd ff:ff:ff:ff:ff:ff
6: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 20:28:18:a1:53:4f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2228:18ff:fea1:534f/64 scope link 
       valid_lft forever preferred_lft forever
7: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-lan state UP qlen 1000
    link/ether 20:28:18:a1:53:4e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2228:18ff:fea1:534e/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by PolynomialDivision** [comment]
@neheb Could you maybe help me fixing the glibc build or give me some hint?

**Comment by neheb** [comment]
> 
> 
> @neheb Could you maybe help me fixing the glibc build or give me some hint?

no idea. i looked into it before but didn't find a solution.

**Comment by PolynomialDivision** [comment]
> > @neheb Could you maybe help me fixing the glibc build or give me some hint?
> 
> no idea. i looked into it before but didn't find a solution.

Okay thanks. I will give it another try. ;)

**Comment by mwarning** [comment]
What is the glibc issue?

**Comment by PolynomialDivision** [comment]
@mwarning https://github.com/OLSR/olsrd/issues/96

**Comment by SvenRoederer** [comment]
Can you change the PR-title to include the new olsr version-number?
Makes following the commit messages more easy.

**Comment by PolynomialDivision** [comment]
> Can you change the PR-title to include the new olsr version-number?

Its a commit hash and no version number. :/

**Comment by SvenRoederer** [comment]
yes I've seen, but probably https://github.com/openwrt/openwrt/commit/4f2243d40a400aa1ce6ae5d06325f93b4d9463a5 gives you some inspiration and is doing as fine as a real version-number

**Pull request merged**
