### PR TITLE
bird{1,2}: Update to version 1.6.8 and 2.0.6

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @Noltari and @tohojo 
Compile tested: mvebu, Turris Omnia, OpenWrt master.

Changelog:
[Version 2.0.6 (2019-09-10)](https://gitlab.labs.nic.cz/labs/bird/blob/v2.0.6/NEWS)
  o RAdv: Solicited unicast RAs
  o BGP: Optional Adj-RIB-Out
  o BGP: Extended optional parameters length
  o Filter: Sets and set expressions in path masks
  o Several important bugfixes

[Version 1.6.8 (2019-09-10)](https://gitlab.labs.nic.cz/labs/bird/blob/v1.6.8/NEWS)
  o Several important bugfixes

### CODE REVIEW

**Comment by tohojo** [comment]
LGTM; thanks! :)

**Comment by BKPepe** [comment]
Would you @jow- or @mwarning merge this, please?

**Comment by BKPepe** [comment]
Thank you.

**Comment by mwarning** [comment]
np :-)

**Pull request merged**
