### PR TITLE
luci-app-bmx6: fixes error line in logread #578

### PR DESCRIPTION
**Pull request by pedro-nonfree**
Signed-off-by: Pedro <pedrowrt@cas.cat>

### CODE REVIEW

**Comment by zorun** [comment]
Can you describe what this fixes and how/why? It should go in the commit message.

**Comment by pedro-nonfree** [comment]
While you have the view bmx6/tunnels opened it fills de logread with `daemon.err uhttpd[pid]: sh: "tunnels":: unknown operand` each time the view is refreshed (5 seconds).

**Comment by pedro-nonfree** [comment]
@zorun OK, explained in the commit, what do you think?

**Comment by zorun** [comment]
Yes thanks!

**Comment by zorun** [comment]
Same thing, this probably should be backported.

**Pull request merged**
