### PR TITLE
bmx6: update version to fix #573 memory leak

### LINKED ISSUE #573: current bmx6 version is affected by a memory leak
@dyangol found that we are hitting a memory leak in our network

```
root@hostname:~# logread | grep -i memo
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300522
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300522
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300522
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300522
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300522
Thu Jun  4 11:28:27 2020 daemon.err bmx6[18464]: Memory leak detected, malloc tag = -300520
```

and looks like is fixed in https://github.com/bmx-routing/bmx6/commit/730b1ca3e98e7e3168242199700b9e90e42e8999 since Apr 25, 2018 but nobody at the moment updated here the feeds (?). Here and now is pointing to a prior version that does not fix the memory leak https://github.com/openwrt-routing/packages/blob/43449bcbbda0582a820acf9f8e2ac20e4ec28137/bmx6/Makefile#L33

### PR DESCRIPTION
**Pull request by pedro-nonfree**
fix #573 

I put WIP because to avoid a fast merge, I don't know if we should increment PKG_RELEASE var

### CODE REVIEW

**Comment by rogerpueyo** [comment]
Hi @pedro-nonfree ,

Thanks for your PR. Could you make the commit title more explicit? For instance:

"bmx6: update version to fix #573 memory leak"

Additionally, add the "Signed-off-by" line, which is nice to keep track of contributions.

Regarding the PKG_RELEASE var, last change from 4 to 5 appeared in [this commit](a3972affe78f433ccb95b876ae596397cf707372) by @altergui . I'm fine with bumping it to 6, but we should maybe ask for @axn 's opinion about it.

**Comment by pedro-nonfree** [comment]
- force pushed new commit
  - [x] "bmx6: update version to fix #573 memory leak"
  - [x] Additionally, add the "Signed-off-by" line, which is nice to keep track of contributions.

**Comment by rogerpueyo** [comment]
After exchanging a couple of mails with Axel, let's increase the PKG_RELEASE now to 6 and, in the future, only increase it when significant changes are introduced (I believe this bugfix is one of them).

@pedro-nonfree , could you please update the commit with `PKG_RELEASE = 6`?

**Comment by pedro-nonfree** [comment]
done :heavy_check_mark:

**Comment by rogerpueyo** [comment]
@pedro-nonfree 

Sorry, I can't merge your commit. It's weird but it seems that I've been kicked out of the openwrt-routing organization :man_shrugging:.

**Comment by zorun** [comment]
Since you are already bumping the version, you need to reset the `PKG_RELEASE` to 1.

**Comment by pedro-nonfree** [comment]
done :heavy_check_mark: 

for curiosity asked about this in freenode/#openwrt-devel and someon said:

> the PKG_RELEASE is our internal version. If there is an external version (e.g.           
PKG_VERSION), then PKG_RELEASE refers to the changes done after this version has been pulled. On each update of the PKG_VERSION, the PKG_RELEASE is set back to 1

**Comment by zorun** [comment]
Good :+1:

It's not a big deal, but yes, it's a lexicographical order (PKG_VERSION comes first, and then PKG_RELEASE indicates successive revisions of the package that are based on the same upstream version)

@pedro-nonfree if this should be backported to 19.07, please open an additional pull request.

**Pull request merged**
