### PR TITLE
batmand: whitespace

### PR DESCRIPTION
**Pull request by yogo1212**

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
LGTM, however, I would improve the commits name, e.g.
batmand: Fix whitespaces
or
batmand: Clean up whitespaces

**Comment by ecsv** [comment]
Seems like some space consistency problems were missed. This is what I found during a quick check:

    diff --git a/batmand/Makefile b/batmand/Makefile
    index 425d355..77497ab 100644
    --- a/batmand/Makefile
    +++ b/batmand/Makefile
    @@ -79,7 +79,7 @@ MAKE_BATGAT_ARGS += \
     	PATH="$(TARGET_PATH)" \
     	SUBDIRS="$(PKG_KMOD_BUILD_DIR)" \
     	LINUX_VERSION="$(LINUX_VERSION)" \
    -	REVISION="$(PKG_REV)" modules	
    +	REVISION="$(PKG_REV)" modules
     
     
     define Build/Configure
    @@ -88,11 +88,11 @@ endef
     ifneq ($(DEVELOPER)$(CONFIG_PACKAGE_batmand),)
     	BUILD_BATMAND := $(MAKE) -C $(PKG_BUILD_DIR) $(MAKE_BATMAND_ARGS)
     endif
    -	
    +
     ifneq ($(DEVELOPER)$(CONFIG_PACKAGE_kmod-batgat),)
     	BUILD_BATGAT := $(MAKE) -C "$(LINUX_DIR)" $(MAKE_BATGAT_ARGS)
     endif
    -	        
    +
     define Build/Compile
     	$(BUILD_BATMAND)
     	cp $(PKG_KMOD_BUILD_DIR)/Makefile.kbuild $(PKG_KMOD_BUILD_DIR)/Makefile
    diff --git a/batmand/files/etc/config/batmand b/batmand/files/etc/config/batmand
    index b84d4a1..0cad38d 100644
    --- a/batmand/files/etc/config/batmand
    +++ b/batmand/files/etc/config/batmand
    @@ -9,4 +9,3 @@ config batmand general
     	option policy_routing_script
     	option disable_client_nat
     	option disable_aggregation
    -
    diff --git a/batmand/files/etc/init.d/batmand b/batmand/files/etc/init.d/batmand
    index 14e8f1a..add4ec8 100644
    --- a/batmand/files/etc/init.d/batmand
    +++ b/batmand/files/etc/init.d/batmand
    @@ -18,10 +18,9 @@ start () {
     	disable_aggregation=$(uci get batmand.general.disable_aggregation)
     	batman_args=""
     
    -	for hna in $hnas
    -		do
    -			batman_args=${batman_args}'-a '$hna' '
    -		done
    +	for hna in $hnas; do
    +		batman_args=${batman_args}'-a '$hna' '
    +	done
     
     	if [ $gateway_class ]; then
     		batman_args=${batman_args}'-g '$gateway_class' '

**Comment by yogo1212** [comment]
@ecsv k. integrated the patch

**Comment by ecsv** [comment]
@yogo1212 The commits are still missing understandable summary lines (what @adrianschmutzler calls "commit names" in his comment)

**Comment by yogo1212** [comment]
@ecsv it really was too late for me last night....

**Comment by ecsv** [comment]
@elektra42 I think this minor cleanup PR is for you.

**Comment by elektra42** [comment]
Thanks!

**Pull request merged**
