### PR TITLE
OONF 0.14.1-1

### PR DESCRIPTION
**Pull request by HRogge**

### CODE REVIEW

**Comment by mwarning** [comment]
@HRogge what is it with all these merge requests of the same name? Are they duplicates?

**Comment by HRogge** [comment]
If I understand your question correctly, they are for different releases of openwrt, which all have (according to my knowledge) different branches in GIT.

**Comment by mwarning** [comment]
The target branches are different. I did not notice that. :-)

**Comment by HRogge** [comment]
Ahh, THAT explains the comment...

I tend to make one commit and then cherry-pick it for the other branches.

**Pull request merged**
