### PR TITLE
cjdns: import package from github.com:SeattleMeshnet/meshbox

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by sbyx** [comment]
Fine with me. Is Lars aware that you are committing this here? If not please put yourself as maintainer.

**Comment by dangowrt** [comment]
I reckon @lgierth will stay the maintainer of the package as he already maintained the package on meshbox. I'm just in the diplomatic mission to arange this inclusion in openwrt-routing as lars is currently busy with other things.

**Comment by lgierth** [comment]
I have a few comments, but need to head out right now. Generally I'm very d'accord with this. /cc @wfleurant @thefinn93

**Comment by wfleurant** [comment]
Lars when you back, an hour or so? Thanks Dan. As everyone knows OpenWrt supports many Target Systems. In turn this PR is very important for our continued development and broad support for users in the OpenWrt community. Thanks again, -w.

**Comment by sbyx** [comment]
Okay cool, since you all seem to be in favor let's merge it.

**Pull request merged**
