### PR TITLE
CI: copy .github from openwrt-packages

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Just copy .github from openwrt enabling:
- checking of formalities
- checking of build
- issue template
- pr template

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@aparcar Could you have a look? ;) Can I just copy this?

**Comment by SvenRoederer** [comment]
Not sure if using the github-templates from OpenWrt-repo, which require mentioning the maintainer, will really work in our repo. From my experience the Maintainer info in the Makefiles is often outdated and PRs are merged by someone with permissions and the mood ...

**Comment by PolynomialDivision** [comment]
We can delete this line. ;)

**Comment by aparcar** [comment]
I think it's fine, no guarantees for the automatic testing.

**Comment by PolynomialDivision** [comment]
> I think it's fine, no guarantees for the automatic testing.

Than go for it. xP

**Comment by aparcar** [comment]
I have no power here.

**Comment by PolynomialDivision** [comment]
@mwarning ;)

**Comment by mwarning** [comment]
Let's give it a shot.

**Pull request merged**
