### PR TITLE
luci-app-cjdns: luci admin support for cjdns-v20.2

### PR DESCRIPTION
**Pull request by wfleurant**
* adds layer 2 and 3 address display column
* fixes switch label pinger
* get version from addr string
* parse addr string for peerStats publicKey

### CODE REVIEW

**Comment by mwarning** [comment]
the signed-off-by line is missing (`git commit -s --amend`)

**Comment by wfleurant** [comment]
# [services/cjdns - view on 17.01]
* PC Engines APU (x86/64 17.LiMe 17.06)

image


# [services/cjdns - view on 18.06]

* TL-WDR3500 (ar71xx/mips32 snapshot)  

image

**Comment by mwarning** [comment]
I don't think I am a good reviewer for changes I know nothing about.
As far as I can tell, it looks ok. Make sure to have the changes tested.
If @lgierth is ok with it, you can maybe take over as maintainer of this package.

**Comment by wfleurant** [comment]
yeah, cheers. ok all for it then... eager to see results from buildbots too :]

**Pull request merged**
