### PR TITLE
oonf: update olsrv2 packages

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
I tested the v15.01, today (just routing and lan_import). Works nice! Not sure, why this was not updated to the newest stable?

**Comment by PolynomialDivision** [comment]
Ping? Noone wants to merge?

**Comment by neheb** [comment]
https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/routing/oonf-olsrd2/compile.txt

**Comment by PolynomialDivision** [comment]
> https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/routing/oonf-olsrd2/compile.txt

Whups. I think it has something to do with the `010-gcc10.patch`. If I remove it, olsrd2 compiles.
Not sure why my buildsystem just skipped the patch when I compiled it. :/

I will have to test on gcc10 again.

**Comment by PolynomialDivision** [comment]
@neheb Do u think adding `-fcommon` is fine to stay compatible with gcc10?

**Pull request merged**
