### PR TITLE
ndppd: bump to 0.2.5

### PR DESCRIPTION
**Pull request by dguglielmi**
*  Remove downstream patches

### CODE REVIEW

**Comment by diizzyy** [comment]
You need to fix the tarball filename
This workaround should work
https://github.com/openwrt/packages/blob/master/sound/fdk-aac/Makefile#L16

**Comment by dguglielmi** [comment]
PR updated using "codeload.github.com".

**Comment by diizzyy** [comment]
PKG_MD5SUM is deprecated, use PKG_HASH instead (SHA256 hash)

**Comment by dguglielmi** [comment]
It's done

**Comment by mwarning** [comment]
Looks good to me and @diizzyy notes has been addressed.

**Pull request merged**
