### PR TITLE
babeld: Update to 1.9.1 and assorted fixes

### PR DESCRIPTION
**Pull request by zorun**

### CODE REVIEW

**Comment by zorun** [comment]
Build- and run-tested on ramips (ZBT WE3526)

**Comment by adrianschmutzler** [comment]
@zorun I'm fine with the additional (already merged) changes.

Off-topic: I'm currently looking into the MAC address assignment of several ramips devices (https://github.com/openwrt/openwrt/pull/2319).
Many of them just have the wan MAC address calculated although it is stored on flash.

Can you check whether you have a MAC address in <&factory 0xe006> and whether it matches your wan (eth0.2) MAC address? If you could provide a hexdump of your factory partition, this would be even better ...

**Comment by zorun** [comment]
@adrianschmutzler err, I don't understand, what does this has to do with babeld?

**Comment by adrianschmutzler** [comment]
@zorun It has nothing to do with babel. I just posted here, because I saw that you own a ZBT WE3526, and the PR was closed anyway.
I mentioned you in the linked PR and will hide the post here.

**Comment by zorun** [comment]
@adrianschmutzler ah, got it

**Pull request merged**
