### PR TITLE
babeld: procd support

### PR DESCRIPTION
**Pull request by imuli**
note: dependant on a change that hasn't been commited to procd yet,
adding support for null arguments.

fixes bug #17

### CODE REVIEW

**Comment by mwarning** [comment]
It would be nice if this could be merged. It seems to be ok from what I read here.

@kerneis bump :-)

**Comment by jech** [comment]
I'll try to release 1.8 before the end of the summer, that will be a good time to merge this change.

**Comment by zorun** [comment]
The change looks good to me, and it would be nice if this is merged before the LEDE release.

Can someone confirm that it indeed works in practice? @imuli ?  I can't test this easily, and I don't like merging without testing.

**Comment by zorun** [comment]
The source of this pull request seems to have disappeared, so I opened a new pull request with Imuli's commit and some changes: #250

**Comment by imuli** [comment]
@zorun I used that patch in production two years ago. It worked then, but I don't have the easy testbed or that job anymore!

**Comment by zorun** [comment]
@imuli Ok, thanks :)

**Pull request closed without merging**
