### PR TITLE
nodogsplash: Version 3.2.1 release

### PR DESCRIPTION
**Pull request by bluewavenet**
Bugfixes and minor enhancements:
  * reset upload/download counter when a client has been authenticated a second time [mwarning]
  * print sesssion duration as 0 in "ndsctl json" and "ndsctl clients" output when a session has not been started [mwarning]
  * rework html templater to speed up splash page generation [mwarning]
  * FAS documentation updates [bluewavenet]
  * Add CSS file and update splash and status html [bluewavenet]

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@mwarning

**Comment by mwarning** [comment]
I've been told that PKG_RELEASE starts a 1.

**Comment by bluewavenet** [comment]
Ooops. We started at 0 last time.

**Comment by mwarning** [comment]
Yeah, that was not correct.

**Pull request merged**
