### PR TITLE
nodogsplash2: update to version 2.0.1

### PR DESCRIPTION
**Pull request by mwarning**
Update to the new bugfix release.

### CODE REVIEW

**Comment by mwarning** [comment]
@bluewavenet please check if this works for you.

**Comment by bluewavenet** [comment]
@mwarning 
If my #343 is merged first then this will be correct?

**Comment by bluewavenet** [comment]
@mwarning 
If my #343 is merged first then this will be correct?

**Comment by mwarning** [comment]
@bluewavenet yes

**Pull request merged**
